#!/bin/bash
#
# Copyright 2017-2020 ZeeZide GmbH. All rights reserved.
#
# swift-lambda -- A collection of SwiftPM extensions to deal with building
#                 AWS Lambda Swift projects.
#

if [ "$DEBUG" = "yes" ]; then
  set -x
fi

SCRIPT_DIR=$(dirname "$0")
SCRIPT_BASENAME=$(basename "$0")

usage() {
  echo "usage: swift lambda <subcommand>"
  echo
  echo "Available subcommands are:"
  echo "   build           Build SPM package as an Amazon Linux Lambda .zip."
  echo "   deploy          Deploy the .zip to Lambda."
  echo "   env             Print environment etc."
  echo
  echo "Try 'swift lambda <subcommand> help' for details."
}

main() {
  if [ $# -lt 1 ]; then
    usage
    exit 1
  fi

  # sanity checks
  SUBCOMMAND="$1"; shift
  
  if test -x "${SCRIPT_DIR}/${SCRIPT_BASENAME}-$SUBCOMMAND"; then
    RUNCMD="${SCRIPT_DIR}/${SCRIPT_BASENAME}-$SUBCOMMAND"
  else
    THECMD="`ls ${SCRIPT_DIR}/${SCRIPT_BASENAME}-${SUBCOMMAND}* | head -n 1`"
    if test -x "${THECMD}"; then
      RUNCMD="${THECMD}"
    else
      echo "Unknown subcommand: '$SUBCOMMAND'"
      echo
      usage
      exit 1
    fi
  fi

  # run command
  . "${RUNCMD}"
}

main "$@"
